### ISSUE TITLE
fail to build on jupyterlab 3.1.7 for @5.0.0

### ISSUE THREAD

**Issue by TermeHansen** [QuantStack/ipysheet#209]
```
jupyter-labextension install ipysheet@0.5
[LabBuildApp] JupyterLab 3.1.7
```

 failing, showing this in log

```
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'ipysheet/style/index.js' in '/home/hafnium/miniconda3/share/jupyter/lab/staging/build'
    at /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1773:28
    at /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:811:13
    at eval (eval at create (/home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:286:22
    at eval (eval at create (/home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:442:22
    at /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:673:25
    at /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:882:8
    at /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
resolve 'ipysheet/style/index.js' in '/home/hafnium/miniconda3/share/jupyter/lab/staging/build'
  Parsed request is a module
  using description file: /home/hafnium/miniconda3/share/jupyter/lab/staging/build/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/hafnium/miniconda3/share/jupyter/lab/staging/build/node_modules doesn't exist or is not a directory
      looking for modules in /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules
        existing directory /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/ipysheet
          using description file: /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/ipysheet/package.json (relative path: .)
            using description file: /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/ipysheet/package.json (relative path: ./style/index.js)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/ipysheet/style/index.js doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/ipysheet/style/index.js.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/ipysheet/style/index.js.json doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/ipysheet/style/index.js.wasm doesn't exist
              as directory
                /home/hafnium/miniconda3/share/jupyter/lab/staging/node_modules/ipysheet/style/index.js doesn't exist
      /home/hafnium/miniconda3/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /home/hafnium/miniconda3/share/jupyter/node_modules doesn't exist or is not a directory
      /home/hafnium/miniconda3/share/node_modules doesn't exist or is not a directory
      /home/hafnium/miniconda3/node_modules doesn't exist or is not a directory
      /home/hafnium/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 2.

```

**Comment by martinRenou** [comment]
You don't need to run this command anymore.

Installing ipysheet with `pip install ipysheet` or `conda install -c conda-forge ipysheet` is enough with JupyterLab 3.

**Comment by TermeHansen** [comment]
why do I then see this:

![image](https://user-images.githubusercontent.com/6922018/130045039-291b2731-951e-4583-ac75-1e199aed2c13.png)

**Comment by TermeHansen** [comment]
```
(base) hafnium@ff4327d62088:~$ conda list | grep -e jupyterlab -e ipysheet
ipysheet                  0.5.0              pyhd8ed1ab_0    conda-forge
jupyterlab                3.1.7              pyhd8ed1ab_0    conda-forge
jupyterlab-widget-ketcher 0.1.4                    pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.7.1              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
```

**Comment by martinRenou** [comment]
I would recommend starting again from a clean conda environment
