### ISSUE TITLE
pip install failed on win7

### ISSUE THREAD

**Issue by oscar6echo** [QuantStack/ipysheet#9]
Below the stack trace.  
It looks like it's the extra "/" at the end of path prevents the installation in folder notebook.d/.
On Windows only. It works fine on macOS.  

```bash
F:\MyTest>pip install ipysheet
Collecting ipysheet
  Downloading https://cdp-artifactory.fr.world.socgen/artifactory/api/pypi/pypi-python-release/packages/66/45/330822c6c85c2ed67818c5d3ffdfc990fd8640087b41c2340bb1b38b5743/ipysheet-0.1.0.tar.gz (585kB)
    100% |████████████████████████████████| 593kB 2.0MB/s
Requirement already satisfied: ipywidgets>=7.0.0 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipysheet)
Requirement already satisfied: traitlets>=4.3.1 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: nbformat>=4.2.0 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: ipykernel>=4.5.1 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: widgetsnbextension~=3.1.0 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: ipython_genutils in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from traitlets>=4.3.1->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: six in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from traitlets>=4.3.1->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: decorator in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from traitlets>=4.3.1->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: jupyter-core in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: tornado>=4.0 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: jupyter-client in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: simplegeneric>0.8 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: setuptools>=18.5 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: pickleshare in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: jedi>=0.10 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: pygments in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: notebook>=4.4.1 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: pyzmq>=13 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: python-dateutil>=2.1 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: parso==0.1.1 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: wcwidth in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: Send2Trash in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: terminado>=0.8.1 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: nbconvert in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: jinja2 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: pywinpty>=0.5; os_name == "nt" in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from terminado>=0.8.1->notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.
0->ipysheet)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: testpath in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: entrypoints>=0.2.2 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: bleach in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: mistune>=0.7.4 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: MarkupSafe>=0.23 in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from bleach->nbconvert->no
tebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Requirement already satisfied: webencodings in c:\homeware\anaconda3-4.4.0-windows-x86_64\lib\site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach-
>nbconvert->notebook>=4.4.1->widgetsnbextension~=3.1.0->ipywidgets>=7.0.0->ipysheet)
Building wheels for collected packages: ipysheet
  Running setup.py bdist_wheel for ipysheet ... error
  Complete output from command C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\oborderi\\AppData\\Local\\Temp\\pip-build-7t4ypee7\\ipysheet\\setup.p
y';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\oborderi\AppData\Local\Temp\tmp4ibkzrywpip-wheel- --py
thon-tag cp36:
  setup.py entered
  $PATH=C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Axalto\Access Client\v5\;C:\Program Files (x86)\G
emalto\Access Client\v5\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\Tools\
Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\ORACLE\Client\11.2.0;C:\Program Files\Freeware\TortoiseGit\1.8.110\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)
\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\oborderi\sgwt-installer\phantomjs\phantomjs-2.1.1-windows\bin;C:\Users\oborderi\sgwt-installer\nodist\bin;C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64;C:\HO
MEWARE\Anaconda3-4.4.0-Windows-x86_64\Library\mingw-w64\bin;C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Library\usr\bin;C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Library\bin;C:\HOMEWARE\Anaconda3-4.4.0-Windows-
x86_64\Scripts;C:\Program Files\Microsoft VS Code\bin;C:\Users\oborderi\AppData\Roaming\npm
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\ipysheet
  copying ipysheet\easy.py -> build\lib\ipysheet
  copying ipysheet\sheet.py -> build\lib\ipysheet
  copying ipysheet\test_all.py -> build\lib\ipysheet
  copying ipysheet\_version.py -> build\lib\ipysheet
  copying ipysheet\__init__.py -> build\lib\ipysheet
  running egg_info
  writing ipysheet.egg-info\PKG-INFO
  writing dependency_links to ipysheet.egg-info\dependency_links.txt
  writing requirements to ipysheet.egg-info\requires.txt
  writing top-level names to ipysheet.egg-info\top_level.txt
  reading manifest file 'ipysheet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'ipysheet.egg-info\SOURCES.txt'
  creating build\lib\ipysheet\static
  copying ipysheet\static\extension.js -> build\lib\ipysheet\static
  copying ipysheet\static\handsontable.js -> build\lib\ipysheet\static
  copying ipysheet\static\index.js -> build\lib\ipysheet\static
  copying ipysheet\static\index.js.map -> build\lib\ipysheet\static
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\ipysheet
  copying build\lib\ipysheet\easy.py -> build\bdist.win-amd64\wheel\.\ipysheet
  copying build\lib\ipysheet\sheet.py -> build\bdist.win-amd64\wheel\.\ipysheet
  creating build\bdist.win-amd64\wheel\ipysheet\static
  copying build\lib\ipysheet\static\extension.js -> build\bdist.win-amd64\wheel\.\ipysheet\static
  copying build\lib\ipysheet\static\handsontable.js -> build\bdist.win-amd64\wheel\.\ipysheet\static
  copying build\lib\ipysheet\static\index.js -> build\bdist.win-amd64\wheel\.\ipysheet\static
  copying build\lib\ipysheet\static\index.js.map -> build\bdist.win-amd64\wheel\.\ipysheet\static
  copying build\lib\ipysheet\test_all.py -> build\bdist.win-amd64\wheel\.\ipysheet
  copying build\lib\ipysheet\_version.py -> build\bdist.win-amd64\wheel\.\ipysheet
  copying build\lib\ipysheet\__init__.py -> build\bdist.win-amd64\wheel\.\ipysheet
  running install_data
  creating build\bdist.win-amd64\wheel\ipysheet-0.1.0.data
  creating build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data
  creating build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data\share
  creating build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data\share\jupyter
  creating build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data\share\jupyter\nbextensions
  creating build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data\share\jupyter\nbextensions\ipysheet
  copying ipysheet\static\handsontable.js -> build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data\share\jupyter\nbextensions\ipysheet
  copying ipysheet\static\extension.js -> build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data\share\jupyter\nbextensions\ipysheet
  copying ipysheet\static\index.js -> build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data\share\jupyter\nbextensions\ipysheet
  copying ipysheet\static\index.js.map -> build\bdist.win-amd64\wheel\ipysheet-0.1.0.data\data\share\jupyter\nbextensions\ipysheet
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\oborderi\AppData\Local\Temp\pip-build-7t4ypee7\ipysheet\setup.py", line 169, in <module>
      setup(**setup_args)
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\site-packages\wheel\bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\site-packages\setuptools\command\install.py", line 61, in run
      return orig.install.run(self)
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\command\install_data.py", line 56, in run
      dir = convert_path(f[0])
    File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\util.py", line 127, in convert_path
      raise ValueError("path '%s' cannot end with '/'" % pathname)
  ValueError: path 'etc/jupyter/nbconfig/notebook.d/' cannot end with '/'

  ----------------------------------------
  Failed building wheel for ipysheet
  Running setup.py clean for ipysheet
Failed to build ipysheet
Installing collected packages: ipysheet
  Running setup.py install for ipysheet ... error
    Complete output from command C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\oborderi\\AppData\\Local\\Temp\\pip-build-7t4ypee7\\ipysheet\\setup
.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\oborderi\AppData\Local\Temp\pip-w18k2qfg-record\in
stall-record.txt --single-version-externally-managed --compile:
    setup.py entered
    $PATH=C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Axalto\Access Client\v5\;C:\Program Files (x86)
\Gemalto\Access Client\v5\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\Tool
s\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\ORACLE\Client\11.2.0;C:\Program Files\Freeware\TortoiseGit\1.8.110\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x8
6)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\oborderi\sgwt-installer\phantomjs\phantomjs-2.1.1-windows\bin;C:\Users\oborderi\sgwt-installer\nodist\bin;C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64;C:\
HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Library\mingw-w64\bin;C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Library\usr\bin;C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Library\bin;C:\HOMEWARE\Anaconda3-4.4.0-Window
s-x86_64\Scripts;C:\Program Files\Microsoft VS Code\bin;C:\Users\oborderi\AppData\Roaming\npm
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\ipysheet
    copying ipysheet\easy.py -> build\lib\ipysheet
    copying ipysheet\sheet.py -> build\lib\ipysheet
    copying ipysheet\test_all.py -> build\lib\ipysheet
    copying ipysheet\_version.py -> build\lib\ipysheet
    copying ipysheet\__init__.py -> build\lib\ipysheet
    running egg_info
    writing ipysheet.egg-info\PKG-INFO
    writing dependency_links to ipysheet.egg-info\dependency_links.txt
    writing requirements to ipysheet.egg-info\requires.txt
    writing top-level names to ipysheet.egg-info\top_level.txt
    reading manifest file 'ipysheet.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'ipysheet.egg-info\SOURCES.txt'
    creating build\lib\ipysheet\static
    copying ipysheet\static\extension.js -> build\lib\ipysheet\static
    copying ipysheet\static\handsontable.js -> build\lib\ipysheet\static
    copying ipysheet\static\index.js -> build\lib\ipysheet\static
    copying ipysheet\static\index.js.map -> build\lib\ipysheet\static
    running install_lib
    creating C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet
    copying build\lib\ipysheet\easy.py -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet
    copying build\lib\ipysheet\sheet.py -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet
    creating C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\static
    copying build\lib\ipysheet\static\extension.js -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\static
    copying build\lib\ipysheet\static\handsontable.js -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\static
    copying build\lib\ipysheet\static\index.js -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\static
    copying build\lib\ipysheet\static\index.js.map -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\static
    copying build\lib\ipysheet\test_all.py -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet
    copying build\lib\ipysheet\_version.py -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet
    copying build\lib\ipysheet\__init__.py -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet
    byte-compiling C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\easy.py to easy.cpython-36.pyc
    byte-compiling C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\sheet.py to sheet.cpython-36.pyc
    byte-compiling C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\test_all.py to test_all.cpython-36.pyc
    byte-compiling C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\_version.py to _version.cpython-36.pyc
    byte-compiling C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\Lib\site-packages\ipysheet\__init__.py to __init__.cpython-36.pyc
    running install_data
    creating C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\share\jupyter\nbextensions\ipysheet
    copying ipysheet\static\handsontable.js -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\share\jupyter\nbextensions\ipysheet
    copying ipysheet\static\extension.js -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\share\jupyter\nbextensions\ipysheet
    copying ipysheet\static\index.js -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\share\jupyter\nbextensions\ipysheet
    copying ipysheet\static\index.js.map -> C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\share\jupyter\nbextensions\ipysheet
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\oborderi\AppData\Local\Temp\pip-build-7t4ypee7\ipysheet\setup.py", line 169, in <module>
        setup(**setup_args)
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\command\install_data.py", line 56, in run
        dir = convert_path(f[0])
      File "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\lib\distutils\util.py", line 127, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'etc/jupyter/nbconfig/notebook.d/' cannot end with '/'

    ----------------------------------------
Command "C:\HOMEWARE\Anaconda3-4.4.0-Windows-x86_64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\oborderi\\AppData\\Local\\Temp\\pip-build-7t4ypee7\\ipysheet\\setup.py';f=getattr(tokenize,
 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\oborderi\AppData\Local\Temp\pip-w18k2qfg-record\install-record.txt --singl
e-version-externally-managed --compile" failed with error code 1 in C:\Users\oborderi\AppData\Local\Temp\pip-build-7t4ypee7\ipysheet\

F:\MyTest>
```

**Comment by SylvainCorlay** [comment]
What is the version of notebook installed into the system?

**Comment by oscar6echo** [comment]
notebook==5.4.0

**Comment by maartenbreddels** [comment]
Yes, it's the traiing slash, I saw it in ipyvolume as well, only affects windows.

**Comment by maartenbreddels** [comment]
0.1.1 should fix this now.

**Comment by oscar6echo** [comment]
It works with 0.1.1.
Thx for the fast response and correction !
